### ISSUE TITLE
CIP: add `spoiler` or `nsfw` attribute to note metadata's attachement

### ISSUE THREAD

**Issue by songkeys** [Crossbell-Box/CIPs#2]
## Motivation

Many social media has the functionality to mark an image or video as spoiler or nsfw for its sensitive content. It will be shown in a blurred form before users clicking to show the actual content.

<details>
<summary> For some examples: </summary>

- Twitter: ![Twitter nsfw image](https://user-images.githubusercontent.com/22665058/180998894-0b6fa2ec-337f-4f39-9dbc-da350226e409.png)
- Discord: 
![Discord spoiler image](https://user-images.githubusercontent.com/22665058/180999176-3be79ac2-9e94-4c7c-a02d-cc25faab598b.png)
- Mastodon: 
![Mastodon nsfw image](https://user-images.githubusercontent.com/22665058/180999502-52776e77-7220-44ec-b7e0-06fe00e188a2.png)

</details>

I think it's helpful to maintain the health of community. It also gives at least an option to let user post some sensitive content in a thoughtful way.

## Proposal

I would like to add an optional `alt` attribute to the element of `attachements` in note's metadata.

```diff
         {
            name?: string
            address?: string
            mime_type?: string
            size_in_bytes?: number

+           /**
+            * The spoiler indicator for medias. Defaults to false.
+            */
+           spoiler?: boolean
          }
```

I'm not sure if `spoiler` or `nsfw` is a better name.

**Comment by Fooooooooooox** [comment]
sounds good

**Comment by songkeys** [comment]
@Fooooooooooox I think we should reopen this for some others' thoughts. This is just a general idea.
